// src/frameworks/lit-html/infra/engine.js
import {render} from 'lit-html';

class UiEngine {
  constructor(element, template) {
    this._template = template;
    this._element = element;
  }

  initialRender(state) {
    return new View({ ...state }, this._element, this._template);
  }
}

class View {
  constructor(state, element, template) {
    this._state = Object.freeze(state);
    this._element = element;
    this._template = template;
    render(template(this._state), element);
  }

  update(updater) {
    const newState = { ...this._state };
    updater(newState);
    return new View(newState, this._element, this._template);
  }
}

export { UiEngine };

// src/frameworks/react/infra/engine.js
import React from "react";
import ReactDOM from "react-dom";

class UIEngine {
  constructor(App, root) {
    this._App = App;
    this._root = root;
  }

  initialRender(state) {
    const component = ReactDOM.render(<this._App state={state} />, this._root);
    return new View(component, state);
  }
}

class View {
  constructor(component, state) {
    this._state = Object.freeze({ ...state });
    this._component = component;
  }

  update(updater) {
    const newState = { ...this._state };
    updater(newState);
    this._component.setState(newState);
    return new View(this._component, newState);
  }
}

export { UIEngine };
