// src/frameworks/react/App.js
import React, { Component } from "react";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { ...props.state, editValue: "" };
  }

  render() {
    const { state } = this;
    const { todos, commands, filter, editValue } = state;
    const completed = todos.filter(t => t.completed);
    const notCompleted = todos.filter(t => !t.completed);
    const list = (filter === "all") ? todos : (filter === "active") ? notCompleted : completed;

    return (
      <section className="todoapp">
        <header className="header" >
          <form onSubmit={(e) => { commands.addTodo(e.target.todo.value); e.preventDefault(); e.target.todo.value = ""; }}>
            <h1>todos</h1>
            <input placeholder="What needs to be done?" name="todo" className="new-todo" />
          </form>
        </header>
        <section className="main">
          <input id="toggle-all" checked={notCompleted.length === 0} type="checkbox" className="toggle-all" onChange={(e) => commands.updateToDos(e.target.checked)} />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {list.map(l =>
              <li key={l.id} className={`todo ${l.completed ? ' completed' : ''} ${l.editing ? ' editing' : ''}`}>
                <div className="view">
                  <input type="checkbox" className="toggle" checked={l.completed} onChange={(e) => commands.updateToDo(l, e.target.checked)} />
                  <label onDoubleClick={() => { this.setState({ editValue: l.title }); commands.edit(l) }}>{l.title}</label>
                  <button className="destroy" onClick={() => commands.removeTodo(l)}></button>
                </div>
                <form onSubmit={(e) => { commands.updateToDoTitle(l, editValue); e.preventDefault(); }} onBlur={() => commands.cancelEdit(l)}>
                  <input name="title" type="text" className="edit" onBlur={() => commands.cancelEdit(l)} value={editValue} onChange={(e) => { this.setState({ editValue: e.target.value }); }} />
                </form >
              </li>)}
          </ul>
        </section>
        {todos.length !== 0 &&
          <footer className="footer">
            <span className="todo-count"><strong>{notCompleted.length}</strong> item(s) left</span>
            <ul className="filters">
              {['all', 'active', 'completed'].map(type =>
                <li key={type}>
                  <a className={`filter ${type === filter ? 'selected' : ''}`} href={`#/${type}`}>{type}</a>
                </li>)}
            </ul>
            {completed.length !== 0 &&
              <button className="clear-completed" onClick={() => commands.removeCompleted()}>
                Clear completed
            </button>}
          </footer>}
      </section>);
  }
}

export default App;

// src/frameworks/vue/App.vue
<template>
  <section class="todoapp">
    <header class="header">
      <div>
        <h1>todos</h1>
        <input
          class="new-todo"
          placeholder="What needs to be done?"
          autofocus
          v-model="newTodo"
          @keyup.enter="addTodo"
        />
      </div>
    </header>
    <section class="main" v-show="state.todos.length">
      <input id="toggle-all" class="toggle-all" type="checkbox" v-model="allDone" />
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        <li
          class="todo"
          v-for="todo in filteredTodos"
          :key="todo.id"
          :class="{completed: todo.completed, editing: todo == editedTodo}"
        >
          <div class="view">
            <input
              class="toggle"
              type="checkbox"
              :checked="todo.completed"
              @input="state.commands.updateToDo(todo, $event.target.checked)"
            />
            <label @dblclick="editTodo(todo)">{{todo.title}}</label>
            <button class="destroy" @click="removeTodo(todo)"></button>
          </div>
          <input
            class="edit"
            type="text"
            v-model="editName"
            v-todo-focus="todo == editedTodo"
            @blur="doneEdit(todo)"
            @keyup.enter="doneEdit(todo)"
            @keyup.esc="cancelEdit(todo)"
          />
        </li>
      </ul>
    </section>

    <footer class="footer" v-show="state.todos.length">
      <span class="todo-count">
        <strong v-text="remaining"></strong> item(s) left
      </span>

      <ul class="filters">
        <li v-for="type in ['all','active','completed']" :key="type">
          <a
            class="filter"
            :href="`#/${type}`"
            :class="{selected: state.filter === type}"
          >{{type}}</a>
        </li>
      </ul>
      <button
        class="clear-completed"
        @click="removeCompleted"
        v-show="state.todos.length > remaining"
      >Clear completed</button>
    </footer>
  </section>
</template>

<script>
const filters = {
  all(todos) {
    return todos;
  },
  active(todos) {
    return todos.filter(todo => !todo.completed);
  },
  completed(todos) {
    return todos.filter(todo => todo.completed);
  }
};

export default {
  props: {
    state: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      newTodo: "",
      editedTodo: null,
      editName: "",
      allDone: false
    };
  },
  methods: {
    addTodo() {
      const { newTodo } = this;
      this.newTodo = "";
      this.state.commands.addTodo(newTodo);
    },
    editTodo(todo) {
      this.editName = todo.title;
      this.editedTodo = todo;
    },
    doneEdit(todo) {
      if (!this.editedTodo) {
        return;
      }
      this.state.commands.updateToDoTitle(todo, this.editName);
      this.editedTodo = null;
    },
    cancelEdit(todo) {
      this.editedTodo = null;
    },
    removeTodo(todo) {
      this.state.commands.removeTodo(todo);
    },
    removeCompleted() {
      this.state.commands.removeCompleted();
    }
  },
  computed: {
    filteredTodos() {
      return filters[this.state.filter](this.state.todos);
    },
    remaining() {
      return filters.active(this.state.todos).length;
    }
  },
  watch: {
    allDone(newValue) {
      this.state.commands.updateToDos(newValue);
    }
  },
  directives: {
    "todo-focus": function(el, binding) {
      if (binding.value) {
        el.focus();
      }
    }
  }
};
</script>

<style src="../../../node_modules/todomvc-common/base.css"/>
<style src="../../../node_modules//todomvc-app-css/index.css"/>
<style src="../../style/style.css"/>
